### POST criar um usuario com todos os dados
POST http://localhost:3000/usuarios/
content-type: application/json

{
  "name": "usuario engraçado",
  "userName": "é verdade",
  "email": "ho@mail",
  "senha": "123"
}

### POST logar no usuario
POST http://localhost:3000/auth/login/
content-type: application/json

{
  "email": "cus@cuz",
  "senha": "123"
}

### GET obter os dados do usuario pelo id
GET http://localhost:3000/usuarios/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjUsImlhdCI6MTcyNTIwMDE5NiwiZXhwIjoxNzI1MjAwNDk2fQ.5OtyBlcVS83VTA6pek_G2SczsWVc9qPxNuIXdxFco-Y

### PATCH atualizar o usuario pelo id
PATCH http://localhost:3000/usuarios/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyNjUzMzY1NiwiZXhwIjoxNzI3MTM4NDU2fQ.6dmC2P1Nx3p2YsOGITvqAWVH6g9qrHezc-FZCH6pgkc
content-type: application/json

{
  "name": "Luzia Varelhas Cruzeta",
  "userName": "chuu",
  "email": "cus@cuz",
}

### DELETE apagar o usuario pelo id
DELETE http://localhost:3000/usuarios/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjksImlhdCI6MTcyNTY0ODc1NiwiZXhwIjoxNzI2MjUzNTU2fQ.kKSKlxr1v7z74LeFXQd94zYBRtpWDe3N1QswoEfX9rA
content-type: application/json

{
  "name": "Luzia Varelhas Cruzeta",
  "userName": "chuu",
  "email": "cus@cuz",
  "senha": "123"
}


### GET obter os dados do usuario pelo id
GET http://localhost:3000/usuarios/profile/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjQsImlhdCI6MTcyNTIyNDQ5NSwiZXhwIjoxNzI1MjI0Nzk1fQ.R_Y5RJprhGXmRBQE8U_8QQiVJ4Vkz7OgqHLIMUV1FlA

### GET obter lugar de id 1
GET http://localhost:3000/lugares/1

### GET obter todos os lugares
GET http://localhost:3000/lugares

### POST criar lugar
POST http://localhost:3000/lugares
content-type: application/json

{
  "descricao": "tem de queijo tem de frango tem de pizza",
  "name": "pastel paulistano",
  "endereco": "ruaserradotombador"
}

### PATCH alterar lugar
PATCH http://localhost:3000/lugares/1
content-type: application/json

{
  "descricao": "pastel chocolate",
  "name": "saltnor alementos",
  "endereco": "i efe erre ene"
}



### DELETE apagar favorito
DELETE http://localhost:3000/favoritos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

### GET obter favorito de id 1
GET http://localhost:3000/favoritos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### GET obter todos os favoritos do usuario de id 1
GET http://localhost:3000/favoritos/usuario/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### GET obter todos os favoritos
GET http://localhost:3000/favoritos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### POST criar favorito
POST http://localhost:3000/favoritos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

{
  "id_usuario": 1,
  "id_lugar": 1
}

### DELETE apagar favorito
DELETE http://localhost:3000/favoritos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json



### DELETE apagar amizade
DELETE http://localhost:3000/amizades/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

### GET obter amizade de id 1
GET http://localhost:3000/amizades/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### GET obter todos os amizades do usuario de id 1
GET http://localhost:3000/amizades/usuario/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### GET obter todos os amizades
GET http://localhost:3000/amizades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0

### POST criar amizade
POST http://localhost:3000/amizades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

{
  "id_emissor": 1,
  "id_receptor": 3,
  "aceito": false
}

### DELETE apagar amizade
DELETE http://localhost:3000/amizades/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

### PATCH alterar amizade
PATCH http://localhost:3000/amizades/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTcyOTk3MTQzMywiZXhwIjoxNzMwNTc2MjMzfQ.eDQnbNgSM6cFwV9yf8pCQCOrLKn43A50mYUnAmToOc0
content-type: application/json

{
  "aceito": true
}