### POST criar um usuario com todos os dados
POST http://localhost:3000/usuarios/
content-type: application/json

{
  "name": "usuario engraçado",
  "userName": "é verdade",
  "email": "ho@mail",
  "senha": "123"
}

### POST logar no usuario
POST http://localhost:3000/auth/login/
content-type: application/json

{
  "email": "joao@email.com",
  "senha": "123"
}

### GET obter os dados do usuario pelo id
GET http://localhost:3000/usuarios/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjQsImlhdCI6MTcyNTIyNTA0NywiZXhwIjoxNzI1MzExNDQ3fQ.n1CDndKJcBTvZ6OdfnzWLGR-3PqFViwAFm0sGuftZrg

### PATCH atualizar o usuario pelo id
PATCH http://localhost:3000/usuarios/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjUsImlhdCI6MTcyNTIwMDE5NiwiZXhwIjoxNzI1MjAwNDk2fQ.5OtyBlcVS83VTA6pek_G2SczsWVc9qPxNuIXdxFco-Y
content-type: application/json

{
  "name": "Luzia Varelhas Cruzeta",
  "userName": "chuu",
  "email": "cus@cuz",
  "senha": "123"
}

### DELETE apagar o usuario pelo id
DELETE http://localhost:3000/usuarios/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjUsImlhdCI6MTcyNTIwMDE5NiwiZXhwIjoxNzI1MjAwNDk2fQ.5OtyBlcVS83VTA6pek_G2SczsWVc9qPxNuIXdxFco-Y
content-type: application/json

{
  "name": "Luzia Varelhas Cruzeta",
  "userName": "chuu",
  "email": "cus@cuz",
  "senha": "123"
}


### GET obter os dados do usuario pelo id
GET http://localhost:3000/usuarios/profile/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjQsImlhdCI6MTcyNTIyNDQ5NSwiZXhwIjoxNzI1MjI0Nzk1fQ.R_Y5RJprhGXmRBQE8U_8QQiVJ4Vkz7OgqHLIMUV1FlA